# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /disk1.1/usr/local/bin/cmake

# The command to remove a file.
RM = /disk1.1/usr/local/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /disk1.1/usr/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ben/git-work/ffff-dnsp2p

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ben/git-work/ffff-dnsp2p

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/disk1.1/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/disk1.1/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/disk1.1/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/disk1.1/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/disk1.1/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/disk1.1/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ben/git-work/ffff-dnsp2p/CMakeFiles /home/ben/git-work/ffff-dnsp2p/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ben/git-work/ffff-dnsp2p/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dnsp2p

# Build rule for target.
dnsp2p: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dnsp2p
.PHONY : dnsp2p

# fast build rule for target.
dnsp2p/fast:
	$(MAKE) -f CMakeFiles/dnsp2p.dir/build.make CMakeFiles/dnsp2p.dir/build
.PHONY : dnsp2p/fast

#=============================================================================
# Target rules for targets named ffff

# Build rule for target.
ffff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ffff
.PHONY : ffff

# fast build rule for target.
ffff/fast:
	$(MAKE) -f CMakeFiles/ffff.dir/build.make CMakeFiles/ffff.dir/build
.PHONY : ffff/fast

#=============================================================================
# Target rules for targets named dht

# Build rule for target.
dht: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dht
.PHONY : dht

# fast build rule for target.
dht/fast:
	$(MAKE) -f dht/CMakeFiles/dht.dir/build.make dht/CMakeFiles/dht.dir/build
.PHONY : dht/fast

#=============================================================================
# Target rules for targets named seccure

# Build rule for target.
seccure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 seccure
.PHONY : seccure

# fast build rule for target.
seccure/fast:
	$(MAKE) -f seccure/CMakeFiles/seccure.dir/build.make seccure/CMakeFiles/seccure.dir/build
.PHONY : seccure/fast

admin.o: admin.c.o
.PHONY : admin.o

# target to build an object file
admin.c.o:
	$(MAKE) -f CMakeFiles/ffff.dir/build.make CMakeFiles/ffff.dir/admin.c.o
.PHONY : admin.c.o

admin.i: admin.c.i
.PHONY : admin.i

# target to preprocess a source file
admin.c.i:
	$(MAKE) -f CMakeFiles/ffff.dir/build.make CMakeFiles/ffff.dir/admin.c.i
.PHONY : admin.c.i

admin.s: admin.c.s
.PHONY : admin.s

# target to generate assembly for a file
admin.c.s:
	$(MAKE) -f CMakeFiles/ffff.dir/build.make CMakeFiles/ffff.dir/admin.c.s
.PHONY : admin.c.s

dns.o: dns.c.o
.PHONY : dns.o

# target to build an object file
dns.c.o:
	$(MAKE) -f CMakeFiles/ffff.dir/build.make CMakeFiles/ffff.dir/dns.c.o
.PHONY : dns.c.o

dns.i: dns.c.i
.PHONY : dns.i

# target to preprocess a source file
dns.c.i:
	$(MAKE) -f CMakeFiles/ffff.dir/build.make CMakeFiles/ffff.dir/dns.c.i
.PHONY : dns.c.i

dns.s: dns.c.s
.PHONY : dns.s

# target to generate assembly for a file
dns.c.s:
	$(MAKE) -f CMakeFiles/ffff.dir/build.make CMakeFiles/ffff.dir/dns.c.s
.PHONY : dns.c.s

ffff.o: ffff.c.o
.PHONY : ffff.o

# target to build an object file
ffff.c.o:
	$(MAKE) -f CMakeFiles/ffff.dir/build.make CMakeFiles/ffff.dir/ffff.c.o
.PHONY : ffff.c.o

ffff.i: ffff.c.i
.PHONY : ffff.i

# target to preprocess a source file
ffff.c.i:
	$(MAKE) -f CMakeFiles/ffff.dir/build.make CMakeFiles/ffff.dir/ffff.c.i
.PHONY : ffff.c.i

ffff.s: ffff.c.s
.PHONY : ffff.s

# target to generate assembly for a file
ffff.c.s:
	$(MAKE) -f CMakeFiles/ffff.dir/build.make CMakeFiles/ffff.dir/ffff.c.s
.PHONY : ffff.c.s

op_get.o: op_get.c.o
.PHONY : op_get.o

# target to build an object file
op_get.c.o:
	$(MAKE) -f CMakeFiles/ffff.dir/build.make CMakeFiles/ffff.dir/op_get.c.o
.PHONY : op_get.c.o

op_get.i: op_get.c.i
.PHONY : op_get.i

# target to preprocess a source file
op_get.c.i:
	$(MAKE) -f CMakeFiles/ffff.dir/build.make CMakeFiles/ffff.dir/op_get.c.i
.PHONY : op_get.c.i

op_get.s: op_get.c.s
.PHONY : op_get.s

# target to generate assembly for a file
op_get.c.s:
	$(MAKE) -f CMakeFiles/ffff.dir/build.make CMakeFiles/ffff.dir/op_get.c.s
.PHONY : op_get.c.s

ops.o: ops.c.o
.PHONY : ops.o

# target to build an object file
ops.c.o:
	$(MAKE) -f CMakeFiles/ffff.dir/build.make CMakeFiles/ffff.dir/ops.c.o
.PHONY : ops.c.o

ops.i: ops.c.i
.PHONY : ops.i

# target to preprocess a source file
ops.c.i:
	$(MAKE) -f CMakeFiles/ffff.dir/build.make CMakeFiles/ffff.dir/ops.c.i
.PHONY : ops.c.i

ops.s: ops.c.s
.PHONY : ops.s

# target to generate assembly for a file
ops.c.s:
	$(MAKE) -f CMakeFiles/ffff.dir/build.make CMakeFiles/ffff.dir/ops.c.s
.PHONY : ops.c.s

properties.o: properties.c.o
.PHONY : properties.o

# target to build an object file
properties.c.o:
	$(MAKE) -f CMakeFiles/ffff.dir/build.make CMakeFiles/ffff.dir/properties.c.o
.PHONY : properties.c.o

properties.i: properties.c.i
.PHONY : properties.i

# target to preprocess a source file
properties.c.i:
	$(MAKE) -f CMakeFiles/ffff.dir/build.make CMakeFiles/ffff.dir/properties.c.i
.PHONY : properties.c.i

properties.s: properties.c.s
.PHONY : properties.s

# target to generate assembly for a file
properties.c.s:
	$(MAKE) -f CMakeFiles/ffff.dir/build.make CMakeFiles/ffff.dir/properties.c.s
.PHONY : properties.c.s

rbtree.o: rbtree.c.o
.PHONY : rbtree.o

# target to build an object file
rbtree.c.o:
	$(MAKE) -f CMakeFiles/ffff.dir/build.make CMakeFiles/ffff.dir/rbtree.c.o
.PHONY : rbtree.c.o

rbtree.i: rbtree.c.i
.PHONY : rbtree.i

# target to preprocess a source file
rbtree.c.i:
	$(MAKE) -f CMakeFiles/ffff.dir/build.make CMakeFiles/ffff.dir/rbtree.c.i
.PHONY : rbtree.c.i

rbtree.s: rbtree.c.s
.PHONY : rbtree.s

# target to generate assembly for a file
rbtree.c.s:
	$(MAKE) -f CMakeFiles/ffff.dir/build.make CMakeFiles/ffff.dir/rbtree.c.s
.PHONY : rbtree.c.s

stub.o: stub.c.o
.PHONY : stub.o

# target to build an object file
stub.c.o:
	$(MAKE) -f CMakeFiles/dnsp2p.dir/build.make CMakeFiles/dnsp2p.dir/stub.c.o
.PHONY : stub.c.o

stub.i: stub.c.i
.PHONY : stub.i

# target to preprocess a source file
stub.c.i:
	$(MAKE) -f CMakeFiles/dnsp2p.dir/build.make CMakeFiles/dnsp2p.dir/stub.c.i
.PHONY : stub.c.i

stub.s: stub.c.s
.PHONY : stub.s

# target to generate assembly for a file
stub.c.s:
	$(MAKE) -f CMakeFiles/dnsp2p.dir/build.make CMakeFiles/dnsp2p.dir/stub.c.s
.PHONY : stub.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... dnsp2p"
	@echo "... edit_cache"
	@echo "... ffff"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... dht"
	@echo "... seccure"
	@echo "... admin.o"
	@echo "... admin.i"
	@echo "... admin.s"
	@echo "... dns.o"
	@echo "... dns.i"
	@echo "... dns.s"
	@echo "... ffff.o"
	@echo "... ffff.i"
	@echo "... ffff.s"
	@echo "... op_get.o"
	@echo "... op_get.i"
	@echo "... op_get.s"
	@echo "... ops.o"
	@echo "... ops.i"
	@echo "... ops.s"
	@echo "... properties.o"
	@echo "... properties.i"
	@echo "... properties.s"
	@echo "... rbtree.o"
	@echo "... rbtree.i"
	@echo "... rbtree.s"
	@echo "... stub.o"
	@echo "... stub.i"
	@echo "... stub.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

